---
swagger: "2.0"
info:
  description: "Administra a movimentação bancaria do correntista e controla o acesso\
    \ atraves de CPF e senha."
  version: "1.0.0"
  title: "ByteBank-Api"
  termsOfService: "http://localhost:8085/bytebank-api/v1/termo-uso"
  contact:
    name: "Suporte"
    url: "http://localhost:8085/bytebank-api/v1/suporte"
    email: "suporte@bytebank-api.com"
host: "localhost:8085"
basePath: "/bytebank-api/v1"
tags:
- name: "cliente"
- name: "conta"
- name: "extrato"
- name: "transacao"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
security:
- BasicAuth: []
paths:
  /cliente:
    post:
      tags:
      - "cliente"
      summary: "Cadastra Cliente"
      description: "Cadastra um novo cliente"
      operationId: "cadastraCliente"
      parameters:
      - in: "body"
        name: "cliente_"
        required: false
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        "201":
          description: "Cadastro efetuado com sucesso"
          schema:
            $ref: "#/definitions/Cliente"
        "400":
          description: "Requisição invalida"
        "500":
          description: "Erro Interno do Servidor"
      x-swagger-router-controller: "Cliente"
  /conta/{agencia}/{numero}/{digito}/saldo:
    get:
      tags:
      - "conta"
      summary: "Consulta Saldo"
      description: "Consulta o saldo da conta do cliente"
      operationId: "consultaSaldo"
      parameters:
      - name: "agencia"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "numero"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "digito"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "Consulta a saldo efetuada com sucesso"
          schema:
            type: "number"
            format: "double"
        "400":
          description: "Requisicao Invalida"
        "401":
          description: "Requisicao não autorizada"
        "500":
          description: "Erro do servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Conta"
  /transacao:
    post:
      tags:
      - "transacao"
      summary: "Cadastra Transacao na conta"
      description: "cadastra uma nova transacao ou deposito na conta"
      operationId: "cadastraTransacao"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "transacao"
        required: true
        schema:
          $ref: "#/definitions/Transacao"
      - name: "tipo"
        in: "query"
        required: true
        type: "string"
        enum:
        - "debito"
        - "deposito"
      responses:
        "201":
          description: "Cadastro efetuado com sucesso"
          schema:
            $ref: "#/definitions/Transacao"
        "400":
          description: "Requisição invalida"
        "401":
          description: "requisicao não autorizada"
        "500":
          description: "Erro Interno do Servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Transacao"
  /extrato/{agencia}/{numero}/{digito}:
    get:
      tags:
      - "extrato"
      summary: "Consulta Extrato"
      description: "Consulta o extrato da conta do cliente"
      operationId: "consultaExtrato"
      parameters:
      - name: "agencia"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "numero"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "digito"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "Consulta a extrato efetuada com sucesso"
          schema:
            $ref: "#/definitions/Extrato"
        "400":
          description: "Requisicao Invalida"
        "401":
          description: "Requisicao não autorizada"
        "500":
          description: "Erro do servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Extrato"
  /transacao/{codigo}:
    put:
      tags:
      - "transacao"
      summary: "Altera Valor da Transação"
      description: "Altera o valor da transação existente na conta do cliente"
      operationId: "alteraValorTransacao"
      parameters:
      - name: "codigo"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "valor"
        in: "query"
        required: true
        type: "number"
        format: "double"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "204":
          description: "Alteração do valor efetuada com sucesso"
        "400":
          description: "Requisição invalida"
        "401":
          description: "requisicao não autorizada"
        "500":
          description: "Erro Interno do Servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Transacao"
    delete:
      tags:
      - "transacao"
      summary: "Exclui a transação"
      description: "Exclusão da Transacao existente na conta do cliente"
      operationId: "excluiTransacao"
      parameters:
      - name: "codigo"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "204":
          description: "Transação Excluida com sucesso"
        "400":
          description: "Requisição invalida"
        "401":
          description: "requisicao não autorizada"
        "500":
          description: "Erro Interno do Servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Transacao"
securityDefinitions:
  BasicAuth:
    type: "basic"
definitions:
  Cliente:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 12345
      titular:
        type: "string"
        example: "Janete Silva"
      cpf:
        type: "string"
        example: "12345678910"
        minLength: 11
        maxLength: 11
      senha:
        type: "string"
        format: "password"
        example: "senha123"
      conta:
        type: "array"
        items:
          $ref: "#/definitions/Conta"
    example:
      senha: "senha123"
      cpf: "12345678910"
      conta:
      - transacoes:
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.027456183070403
          id: 0
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.027456183070403
          id: 0
        numero: 123456
        saldo: 101.34
        agencia: 1234
        digito: 0
      - transacoes:
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.027456183070403
          id: 0
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.027456183070403
          id: 0
        numero: 123456
        saldo: 101.34
        agencia: 1234
        digito: 0
      id: 12345
      titular: "Janete Silva"
  Conta:
    type: "object"
    properties:
      agencia:
        type: "integer"
        format: "int32"
        example: 1234
      numero:
        type: "integer"
        format: "int64"
        example: 123456
      digito:
        type: "integer"
        format: "int32"
        example: 0
      saldo:
        type: "number"
        format: "double"
        example: 101.34
      cliente:
        $ref: "#/definitions/Cliente"
      transacoes:
        type: "array"
        items:
          $ref: "#/definitions/Transacao"
    example:
      transacoes:
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.027456183070403
        id: 0
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.027456183070403
        id: 0
      numero: 123456
      saldo: 101.34
      agencia: 1234
      digito: 0
  Transacao:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      tipo:
        type: "string"
        enum:
        - "debito"
        - "deposito"
      valor:
        type: "number"
        format: "double"
      data:
        type: "string"
        format: "date-time"
      conta:
        $ref: "#/definitions/Conta"
    example:
      tipo: "debito"
      data: "2000-01-23T04:56:07.000+00:00"
      valor: 6.027456183070403
      id: 0
  Extrato:
    type: "object"
    properties:
      transacoes:
        type: "array"
        items:
          $ref: "#/definitions/Transacao"
    example:
      transacoes:
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.027456183070403
        id: 0
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.027456183070403
        id: 0
